    public enum MyCombatAudioLibrarySounds {
        flipsfx,
        heavyhitland,
        lighthitfistwhoosh,
        lighthitland,
        whoosh,
        lastninjamenuvoices,
        buttonclick,
        menuopenclose,
        buttonpress,
        enemy1die,
        enemy1lightimpact,
        enemy1lightpain,
        enemy1medpain,
        enemy1vocals,
        tieronedrivestrike,
        chargedrivestrikecomplete,
        toss,
        landthrown,
        throwVocal1,
        fsteps_track,
        fsteps_grass,
        pickupItem,
        lightCry,
        fsteps_water,
        fsteps_rock
    }
    public enum MyCombatAudioLibraryMusic {
        Level1TheWastelands,
        Level1TheWastelandsLoader
    }
